from django.bd import models


class Movie(models.Model):
    title = models.Charfield(max_lenth=200)
    year = models.DateField()
    movie_type = models.Charfield(max_lenth=200)
    actors = models.Charfield(max_lenth=200)
    awards = models.Charfield(max_lenth=200)
    country =models.Charfield(max_lenth=200)
    director =models.Charfield(max_lenth=200)
    genre =models.Charfield(max_lenth=200)
    language =models.Charfield(max_lenth=200)
    metascore =models.Charfield(max_lenth=200)
    plot =models.Charfield(max_lenth=200)
    poster =models.Charfield(max_lenth=200)
    rated =models.Charfield(max_lenth=200)
    ratings =models.Charfield(max_lenth=200)
    released =models.Charfield(max_lenth=200)
    runtime =models.Durationfield()
    writer =models.Charfield(max_lenth=200)
    imdb_ID =models.Charfield(max_lenth=200)
    imdb_Rating =models.Charfield(max_lenth=200)
    imdb_Votes =models.Charfield(max_lenth=200)
    box_office =models.Charfield(max_lenth=200)
    production =models.Charfield(max_lenth=200)
    website =models.Charfield(max_lenth=200)
    tom_Consensus =models.Charfield(max_lenth=200)
    tom_Fresh =models.Charfield(max_lenth=200)
    tom_Image =models.Charfield(max_lenth=200)
    tom_Meter =models.Charfield(max_lenth=200)
    tom_Rating =models.Charfield(max_lenth=200)
    tom_Reviews =models.Charfield(max_lenth=200)
    tom_Rotten =models.Charfield(max_lenth=200)
    tom_UserMeter =models.Charfield(max_lenth=200)
    tom_UserRating =models.Charfield(max_lenth=200)
    tom_UserReviews =models.Charfield(max_lenth=200)

    torrent = models.FileField()


class Series(models.Model):
    title = models.Charfield(max_lenth=200)
    year = models.DateField()
    movie_type = models.Charfield(max_lenth=200)
    actors = models.Charfield(max_lenth=200)
    awards = models.Charfield(max_lenth=200)
    country = models.Charfield(max_lenth=200)
    director = models.Charfield(max_lenth=200)
    genre = models.Charfield(max_lenth=200)
    episode = models.Charfield(max_lenth=200)
    season = models.Charfield(max_lenth=200)
    series_ID = models.Charfield(max_lenth=200)
    language = models.Charfield(max_lenth=200)
    metascore = models.Charfield(max_lenth=200)
    plot = models.Charfield(max_lenth=200)
    poster = models.Charfield(max_lenth=200)
    rated = models.Charfield(max_lenth=200)
    ratings = models.Charfield(max_lenth=200)
    released = models.Charfield(max_lenth=200)
    runtime = models.Charfield(max_lenth=200)
    writer = models.Charfield(max_lenth=200)
    imdb_ID = models.Charfield(max_lenth=200)
    imdb_Rating = models.Charfield(max_lenth=200)
    imdb_Votes = models.Charfield(max_lenth=200)
    box_office = models.Charfield(max_lenth=200)
    production = models.Charfield(max_lenth=200)
    website = models.Charfield(max_lenth=200)
    tom_Consensus = models.Charfield(max_lenth=200)
    tom_Fresh = models.Charfield(max_lenth=200)
    tom_Image = models.Charfield(max_lenth=200)
    tom_Meter = models.Charfield(max_lenth=200)
    tom_Rating = models.Charfield(max_lenth=200)
    tom_Reviews = models.Charfield(max_lenth=200)
    tom_Rotten = models.Charfield(max_lenth=200)
    tom_UserMeter = models.Charfield(max_lenth=200)
    tom_UserRating = models.Charfield(max_lenth=200)
    tom_UserReviews = models.Charfield(max_lenth=200)

    torrent = models.FileField()
